name: GitHub Actions Demo
run-name: ${{ github.actor }} is building the toolchain for mac ðŸš€
on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  docker-toolchain:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: ðŸ”¨ Build and Push Native ARM64 Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false # Set to true to push
          # This build will be extremely fast because it is running on native ARM64 hardware
          platforms: linux/arm64